service:
  name: todo-serverless

package:
  excludeDevDependencies: true
  include:
    - "package.json"
    - "!node_modules/aws-sdk/**"

custom:
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  # Custom config for Jetpack
  jetpack:
    preInclude:
      - "!**"
    include:
      - "**"
      - "!node_modules/aws-sdk/**"
      - "package.json"
    trace:
      ignores:
        - "aws-sdk"
        - "middy"
    dynamic:
      bail: true
  # Topic Name for SNS
  topicName: imagesTopic-${self:provider.stage}
  queueName: get-todos-${self:provider.stage}
  streamName: todosStream-${self:provider.stage}
  # Documentation for the API
  documentation:
    api:
      info:
        version: v1.0.0
        title: Todo API
        description: Serverless todo app
    models:
      - name: CreateTodoRequest
        contentType: application/json
        schema: ${file(validators/create-todo-request.json)}
      - name: UpdateTodoRequest
        contentType: application/json
        schema: ${file(validators/update-todo-request.json)}
  # Dev and Prod stages
  defaultStage: dev
  profiles:
    dev: default
    prod: prod
  # Prune previous versions of artifacts
  prune:
    automatic: true
    number: 3

  dynamodb:
    start:
      port: ${env:DYNAMODB_PORT, 8000}
      host: ${env:DYNAMODB_HOST, localhost}
      migrate: true
      noStart: ${env:DYNAMODB_NO_START, false}
    stages:
      - ${self:provider.stage}
    capacities:
      - table: Todos-Serverless-${self:provider.stage}
        index: userIdIndex
provider:
  name: aws
  # Logs for websocket
  logs:
    websocket:
      level: ERROR
  # Runtime for NodeJS
  runtime: nodejs12.x
  region: us-east-2
  stage: ${opt.stage, 'dev'}
  profile: ${self:custom.profiles.${self:provider.stage}}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  # Make Deployment Bucket AES256
  deploymentBucket:
    serverSideEncryption: AES256
  # Setup environment
  environment:
    DEBUG: "*"
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    SERVERLESS_STAGE: ${self:provider.stage}
    TODOS_TABLE: Todos-Serverless-${self:provider.stage}
    USER_ID_INDEX: UserIdIndex
    ATTACHMENTS_BUCKET: attachments-urls-${self:provider.stage}-${self:provider.region}
    CONNECTIONS_TABLE: Connections-${self:provider.stage}-${self:provider.region}
    SIGNED_URL_EXPIRATION: 300
    AUTH_0_SECRET_ID: Auth0Secret-${self:provider.stage}
    AUTH_0_SECRET_FIELD: auth0Secret
    AUTH0_CLIENT_SECRET: ${env:AUTH0_CLIENT_SECRET}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: !Ref Auth0Secret
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource: !GetAtt KMSKey.Arn
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: arn:aws:sns:${self:provider.region}:#{AWS::AccountId}64:${self:custom.topicName}-${self:provider.stage}
    - Effect: Allow
      Action:
        - kinesis:GetRecords
        - kinesis:GetShardIterator
        - kinesis:DescribeStream
        - kinesis:ListStreams
        - kinesis:PutRecord
        - kinesis:PutRecords
      Resource:
        Fn::GetAtt:
          - todosStream
          - Arn
  # XRay Tracing active
  tracing:
    lambda: true
    apiGateway: true

functions:
  RS256:
    tracing: Active
    handler: src/lambda/auth/RS256Auth0Authorizer.handler
    iamRoleStatementsInherit: true
    events:
      - sqs:
          arn:
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - authorizer-user
  GetTodos:
    tracing: Active
    handler: src/lambda/functions/GetTodos.default
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.USER_ID_INDEX}
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: arn:aws:s3:::${self:provider.environment.ATTACHMENTS_BUCKET}/*
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"
      - Effect: Allow
        Action:
          - logs:CreateLogStream
          - logs:CreateLogGroup
          - logs:PutLogEvents
        Resource: "*"
    events:
      - http:
          method: get
          path: /todos
          cors: true
          allowCredentials: true
          authorizer: RS256
      - sqs:
          arn:
            Fn::GetAtt:
              - GetTodoQueue
              - Arn

  CreateTodo:
    tracing: Active
    handler: src/lambda/functions/NewTodo.default
    iamRoleStatementsInherit: true
    events:
      - http:
          method: post
          path: /todos
          cors: true
          allowCredentials: true
          authorizer: RS256
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new todo item
            description: Create and insert item into todo table
            requestModels:
              'application/json': CreateTodoRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.USER_ID_INDEX}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"
      - Effect: Allow
        Action:
          - logs:CreateLogStream
          - logs:CreateLogGroup
          - logs:PutLogEvents
        Resource: "*"
  UpdateTodo:
    tracing: Active
    handler: src/lambda/functions/UpdateTodo.default
    events:
      - http:
          method: patch
          path: todos/{todoId}
          cors: true
          authorizer: RS256
          allowCredentials: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Update a new todo item
            description: Update and insert item into todo table
            requestModels:
              'application/json': UpdateTodoRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.USER_ID_INDEX}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"
      - Effect: Allow
        Action:
          - logs:CreateLogStream
          - logs:CreateLogGroup
          - logs:PutLogEvents
        Resource: "*"
  DeleteTodo:
    tracing: Active
    handler: src/lambda/functions/DeleteTodo.default
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true
          authorizer: RS256
          allowCredentials: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.USER_ID_INDEX}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"
      - Effect: Allow
        Action:
          - logs:CreateLogStream
          - logs:CreateLogGroup
          - logs:PutLogEvents
        Resource: "*"
  GenerateUploadUrl:
    tracing: Active
    handler: src/lambda/functions/GenerateUploadUrl.default
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment
          cors: true
          authorizer: RS256
          allowCredentials: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.USER_ID_INDEX}
      - Effect: Allow
        Action:
        - s3:PutObject
        - s3:GetObject
        Resource: arn:aws:s3:::${self:provider.environment.ATTACHMENTS_BUCKET}/*
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"
      - Effect: Allow
        Action:
          - logs:CreateLogStream
          - logs:CreateLogGroup
          - logs:PutLogEvents
        Resource: "*"
  ConnectHandler:
    tracing: Active
    handler: src/lambda/websocket/Connect.handler
    events:
      -
        websocket:
          route: "$connect"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:PutItem
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CONNECTIONS_TABLE}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"
      - Effect: Allow
        Action:
          - logs:CreateLogStream
          - logs:CreateLogGroup
          - logs:PutLogEvents
        Resource: "*"
  DisconnectHandler:
    tracing: Active
    handler: "src/lambda/websocket/Disconnect.handler"
    events:
      -
        websocket:
          route: "$disconnect"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:PutItem
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CONNECTIONS_TABLE}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"
      - Effect: Allow
        Action:
          - logs:CreateLogStream
          - logs:CreateLogGroup
          - logs:PutLogEvents
        Resource: "*"
  SendUploadNotifications:
    tracing: Active
    environment:
      STAGE: ${self:provider.stage}
      API_ID:
        Ref: WebsocketsApi
    handler: src/lambda/s3/SendNotification.handler
    events:
      -
        sns:
          arn:
            Fn::Join:
              - ":"
              -
                - arn:aws:sns
                -
                  Ref: AWS::Region
                -
                  Ref: AWS::AccountId
                - ${self:custom.topicName}
          topicName: ${self:custom.topicName}

resources:
  - ${file(./services/apigateway/gateway.yml)}
  - ${file(./services/uploads/s3bucket.yml)}
  - ${file(./services/dynamodb/dynamodb.yml)}
  - ${file(./services/dynamodb/connections.yml)}
  - ${file(./services/sns/snsTopics.yml)}
  - ${file(./services/kmskey/kms.yml)}
  - ${file(./services/sqs/queues.yml)}
  - ${file(./services/kinesis/stream.yml)}

plugins:
  - serverless-jetpack
  - serverless-plugin-typescript
  - serverless-step-functions
  - serverless-prune-plugin
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-iam-roles-per-function
  - serverless-plugin-warmup
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline
