Resources:
  ImagesTopics:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Image bucket topic
      TopicName: ${self:custom.topicName}

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: sns:Publish
            Resource:
              !Ref ImagesTopics
            Condition:
              ArnLike:
                AWS:SourceArn: arn:aws:s3:::${self:provider.environment.ATTACHMENTS_BUCKET}
      Topics:
        - !Ref ImagesTopics

